spring:
  application:
    name: UserTest
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  cache:
    type: redis
  
  redis:
    host: localhost
    port: 6379
    
  jpa:
    show-sql: true

  cloud:
    config:
      import-check:
        enabled: false
      
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: 8080
  host: localhost
  connectionTimeout: 5000


management:
  endpoint:
    env:
      show-values: ALWAYS
  endpoints:
    web:
      exposure:
        #include: '*'  # Expose all endpoints
        include: health, info, beans, env, configprops, refresh

resilience4j:
  circuitbreaker:
    instances:
      getCountriesCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 10
  ratelimiter:
    instances:
      getCountriesRateLimiter:
        limitForPeriod: 2          # Max 5 calls allowed
        limitRefreshPeriod: 60s    # Refresh limit every 10 sec
        timeoutDuration: 1s        # Wait max 2 sec if limit exceeded
        registerHealthIndicator: true

logging:
  level:
    io.github.resilience4j: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

