spring:
  application:
    name: userInfoService
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    config:
      import-check:
        enabled: false
      
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: 8085
  host: localhost
  connectionTimeout: 5000


management:
  endpoint:
    env:
      show-values: ALWAYS
  endpoints:
    web:
      exposure:
        #include: '*'  # Expose all endpoints
        include: health, info, beans, env, configprops, refresh

logging:
  level:
    io.github.resilience4j: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

